# Reference : 
# [1] https://levelup.gitconnected.com/docker-compose-made-easy-with-elasticsearch-and-kibana-4cb4110a80dd
# [2] https://quoeamaster.medium.com/deploying-elasticsearch-and-kibana-with-docker-86a4ac78d851

# Official docs : https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html

version: "3.8"
services:
  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - xpack.security.enabled=false
      # "discovery.type=single-node" is for development purpose
      - "discovery.type=single-node"
    networks:
      - elasticsearch-kibana-network
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-container:9200
    networks:
      - elasticsearch-kibana-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elasticsearch-kibana-network:
    driver: bridge
