version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: mern-io-server_ctr
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI:
      JWT_SECRET:
      JWT_EXPIRY: 1d
    ports:
      - 5000:5000
