version: '3.8'

services:
  gitlab-web:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    hostname: "gitlab.example.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.example.com"