version: "3.8"

services:
  ip-getter:
    build:
      context: .
      dockerfile: Dockerfile
    image: ip-getter_img
    container_name: ip-getter_ctr
    environment:
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
    ports:
     - 5000:5000
