version: "3.8"

services:
  ip-getter:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: ip-getter_dev_img
    container_name: ip-getter__dev_ctr
    environment:
      HOSTNAME: ${HOSTNAME:-localhost}
      PORT: ${PORT:-5000}
    ports:
      - 5000:5000
