version: "3.8"

services:
  cloudbeaver-web:
    image: dbeaver/cloudbeaver:21.2.4
    container_name: cloudbeaver-ctr
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
    ports:
      - 8080:8978
