# Reference for environment variables in docker-compose : https://stackoverflow.com/a/50201232
version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      HOST: ${HOST}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
  mydb:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}