version: "3.8"

services:
  fastify-crud-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify_crud_api_ctr
    environment:
      PORT: ${PORT:-5000}
    ports:
      - 5000:5000
